version: '3.3'
services:
  phx:
    image: phx
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
      args:
        - MIX_ENV=dev
#        - MIX_ENV=prod
    volumes:
      - ../../app:/app
      - shared:/shared
#      - ../../docker:/app/docker
  db:
    image: mariadb
    volumes:
      - mydata:/var/lib/mysql
      - shared:/shared
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  mydata:
  shared:
