#!/bin/bash

# for dev we do deps build/compile at run time since we are importing the volume

################################################

if [ ! -d deps -o ! -d _build ]; then
    rm -rf _build deps # cleanup
fi


if [[ mix.exs -nt mix.lock || ! -d _build ]]; then
    echo "===> Detected need for recompile..."
	rm -rf /root/.cache
	mix deps.get || exit 1
	mix deps.compile || exit 1
fi

if [ -d assets/node_modules ]; then
    echo ""
    echo "===> Not rebuilding assets -- if desired: rm -rf src/assets/node_modules"
    echo ""
else
    echo "===> Rebuilding assets"
    (cd assets; npm install)
fi

echo "===> starting phoenix in dev mode..."
mix ecto.create

echo "===> starting phoenix in dev mode..."
exec mix phx.server
