version: '3.3'
services:
  phx:
    image: phx
    build:
      context: ../..
      dockerfile: docker/prd/Dockerfile
      args:
        - MIX_ENV=prod
    ports:
      - "5000:5000"
  db:
    image: mariadb
    volumes:
      - mydata:/var/lib/mysql
volumes:
  mydata:
