version: '3.3'
services:
  phx:
    image: phx
    build:
      context: ../..
      dockerfile: docker/tst/Dockerfile
      args:
        - MIX_ENV=dev
#        - MIX_ENV=prod
    volumes:
      - shared:/shared
    ports:
      - "4000:4000"
  db:
    image: mariadb
    volumes:
      - mydata:/var/lib/mysql
      - shared:/shared
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  mydata:
  shared:
